import Header from "@/components/Header";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-black min-h-screen">
        <main>
          <div className="bg-zinc-900 max-w-7xl border-zinc-800  border-r-2 border-l-2 mx-auto min-h-screen text-white">
            <Header/>
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
